In [3]:
#Import torch
import torch

#Create random tensor
random_tensor= torch.rand(7,7)




In [4]:
tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)
tensor_2_transposed = tensor_2.T
result = torch.matmul(tensor_1, tensor_2_transposed)

In [23]:
torch.manual_seed(0)

tensor_1 = torch.rand(7, 7)

tensor_2 = torch.rand(1, 7)

tensor_2_transposed = tensor_2.T

result = torch.matmul(tensor_1, tensor_2_transposed)

print(result, result.size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [6]:
torch.cuda.manual_seed(1234)

In [8]:
device = torch.device('cuda')
print(f"Device: {device}")

tensor_1 = torch.rand(2, 3, device=device)
tensor_2 = torch.rand(2, 3, device=device)

#print(tensor_1)
#print(tensor_2)


Device: cuda


In [25]:
result = torch.matmul(tensor_1, tensor_2.T)

print(result)
print(result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


In [18]:
max_value = torch.max(result)
min_value = torch.min(result)

In [24]:
max_index = torch.argmax(result)

min_index = torch.argmin(result)

print(f"Index of Maximum Value: {max_index}")
print(f"Index of Minimum Value: {min_index}")

Index of Maximum Value: 3
Index of Minimum Value: 4


In [22]:
#set seed
torch.manual_seed(7)

#create random tensor
tensor_1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_2 = tensor_1.squeeze()

#print the first tensor and shape
print(f"Tensor 1:\n{tensor_1}")
print(f"Shape of Tensor 1: {tensor_1.shape}")

#print the second tensor and shape
print(f"Tensor 2:\n{tensor_2}")
print(f"Shape of Tensor 2: {tensor_2.shape}")


Tensor 1:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Tensor 1: torch.Size([1, 1, 1, 10])
Tensor 2:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Tensor 2: torch.Size([10])
